### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by fabrizio0000** [t00ts/maverick#2]
Hey man, congratulations for you work! 
It's not clear to me how can I install the software

**Comment by t00ts** [comment]
Apologies @fabrizio0000, you're right.

We accidentally removed the contact information from the `README.md` on our last commit.

Please send an email to abel `at` jupiter-labs.tech or find me on [Telegram](https://t.me/abel_maverick).

I'll be happy to get you onboarded ASAP.
